name: xconn
description: WAMP v2 Client and Router for Dart.
version: 0.1.0
repository: https://github.com/xconnio/xconn-dart

environment:
  sdk: ">=2.17.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  wampproto:
    # ignore: invalid_dependency
    git: https://github.com/xconnio/wampproto-dart/
  web_socket_channel: ^3.0.0
  yaml: 3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
